!define IMPORT https://raw.githubusercontent.com/FrancescoSprotetto/component-plantum-library/main
!includeurl IMPORT/Import.puml
!include images/azure.puml
!include images/qarc.puml
!include images/tomcat.puml
!include images/sybase.puml
!include images/gemalto.puml
!include images/filenet.puml
!include images/jms.puml
!include images/kaleyra.puml
!include images/lc.puml

' Colors
' ##################################

!define ELEMENT_FONT_COLOR #FFFFFF
!define ORACLE_BK_COLOR #710000
!define VUEJS_BK_COLOR #41B883
!define AZURE_BK_COLOR #008AD7
!define QARC_BK_COLOR #FE7D19
!define TOMCAT_BK_COLOR #FFDC76
!define SYBASE_BK_COLOR #007DB8
!define GEMALTO_BK_COLOR #ED7E1F
!define FILENET_BK_COLOR #006290
!define JMS_BK_COLOR #E10000
!define KALEYRA_BK_COLOR #D81D3A
!define LC_BK_COLOR #1D87C3

' Styling
' ##################################

!define TECHN_FONT_SIZE 12

skinparam defaultTextAlignment center

' ###################################
' ORACLE
' ###################################

skinparam rectangle<<oracle_module>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor ORACLE_BK_COLOR
    BorderColor ORACLE_BK_COLOR
}

!define OracleModule(e_alias, e_label, e_ci) rectangle "==<<e_label>>\n\n e_ci\n\n <$oracle_original>" <<oracle_module>> as e_alias


' ###################################
' ORACLE DB
' ###################################

skinparam database<<oracle_db>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor ORACLE_BK_COLOR
    BorderColor ELEMENT_FONT_COLOR
}

!define OracleDb(e_alias, e_label, e_ci) database "==<<e_label>>\n\n e_ci\n\n <$oracle_original>" <<oracle_db>> as e_alias


' ###################################
' VUEJS
' ###################################

skinparam rectangle<<vuejs_module>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor VUEJS_BK_COLOR
    BorderColor VUEJS_BK_COLOR
}

!define VueJSModule(e_alias, e_label, e_ci) rectangle "==<<e_label>>\n\n e_ci\n\n <$vuejs_wordmark>" <<vuejs_module>> as e_alias

' ###################################
' AZURE
' ###################################

skinparam rectangle<<azure_module>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor AZURE_BK_COLOR
    BorderColor AZURE_BK_COLOR
}

!define AzureModule(e_alias, e_label, e_ci) rectangle "==<<e_label>>\n\n e_ci\n\n <$azure>" <<azure_module>> as e_alias

' ###################################
' QARC
' ###################################

skinparam rectangle<<qarc_module>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor QARC_BK_COLOR
    BorderColor QARC_BK_COLOR
}

!define QarcModule(e_alias, e_label, e_ci) rectangle "==<<e_label>>\n\n e_ci\n\n <$qarc>" <<qarc_module>> as e_alias

' ###################################
' TOMCAT
' ###################################

skinparam rectangle<<tomcat_module>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor TOMCAT_BK_COLOR
    BorderColor TOMCAT_BK_COLOR
}

!define TomcatModule(e_alias, e_label, e_ci) rectangle "==<<e_label>>\n\n e_ci\n\n <$tomcat>" <<tomcat_module>> as e_alias

' ###################################
' SYBASE
' ###################################

skinparam database<<sybase_db>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor SYBASE_BK_COLOR
    BorderColor SYBASE_BK_COLOR
}

!define SybaseDb(e_alias, e_label, e_ci) database "==<<e_label>>\n\n e_ci\n\n <$sybase>" <<sybase_db>> as e_alias

' ###################################
' GEMALTO
' ###################################

skinparam rectangle<<gemalto_module>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor GEMALTO_BK_COLOR
    BorderColor GEMALTO_BK_COLOR
}

!define GemaltoModule(e_alias, e_label, e_ci) rectangle "==<<e_label>>\n\n e_ci\n\n <$gemalto>" <<gemalto_module>> as e_alias

' ###################################
' FILENET
' ###################################

skinparam rectangle<<filenet_module>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor FILENET_BK_COLOR
    BorderColor FILENET_BK_COLOR
}

!define FilenetModule(e_alias, e_label, e_ci) rectangle "==<<e_label>>\n\n e_ci\n\n <$filenet>" <<filenet_module>> as e_alias

' ###################################
' JMS
' ###################################

skinparam queue<<jms_queue>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor JMS_BK_COLOR
    BorderColor JMS_BK_COLOR
}

!define JmsQueue(e_alias, e_label, e_ci) queue "==<<e_label>>\n\n e_ci\n\n <$jms>" <<jms_queue>> as e_alias

' ###################################
' KALEYRA
' ###################################

skinparam rectangle<<kaleyra_module>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor KALEYRA_BK_COLOR
    BorderColor KALEYRA_BK_COLOR
}

!define KaleyraModule(e_alias, e_label, e_ci) rectangle "==<<e_label>>\n\n e_ci\n\n <$kaleyra>" <<kaleyra_module>> as e_alias

' ###################################
' LC
' ###################################

skinparam rectangle<<lc_module>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor LC_BK_COLOR
    BorderColor LC_BK_COLOR
}

!define LcModule(e_alias, e_label, e_ci) rectangle "==<<e_label>>\n\n e_ci\n\n <$lc>" <<lc_module>> as e_alias