!define IMPORT https://raw.githubusercontent.com/FrancescoSprotetto/component-plantum-library/main
!includeurl IMPORT/Import.puml

' Colors
' ##################################

!define ELEMENT_FONT_COLOR #FFFFFF
!define ORACLE_BK_COLOR #710000

' Styling
' ##################################

!define TECHN_FONT_SIZE 12

skinparam defaultTextAlignment center

' ###################################
' ORACLE
' ###################################

skinparam rectangle<<oracle_module>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor #710000
    BorderColor #710000
}

!define OracleModule(e_alias, e_label, e_ci) rectangle "==e_label\n\n e_ci\n\n <$oracle_original>" <<oracle_module>> as e_alias


' ###################################
' ORACLE DB
' ###################################

skinparam database<<oracle_db>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor #710000
    BorderColor ELEMENT_FONT_COLOR
}

!define OracleDb(e_alias, e_label, e_ci) database "==e_label\n\n //<size:TECHN_FONT_SIZE>[e_techn]</size>// e_ci\n\n <$oracle_original>" <<oracle_db>> as e_alias
