@startuml
sprite $azure [600x315/16z] {
xThBRLr144F1FJUJVxOEmBy7DGY9G9qGxXHeI-htGP8aIP8aIP8aIPAav2qah4JLWYjX9MN2bR2IKd0bgWgiX5N1bR1QS2Mif6ou4bQYQi6Li98ouKfOIIcu
4bK5LiBgUrm9gnisOPNIjRkm-hqSO8cgv7hlBkLZLmLOmkhaIbYbSPiihCwkHDNl5Qv8XTNbta_AzxiILWTOmghXIbZTR_v4rU_LR_w4rUTNVr8EStM59Qm-
ToNbxWgitwFgyC_WpPMm-loMHih1LGkMiEBgzvI3go_24bLv1rV2wZ1N1rZ2wk1AM9tc2YobC5TWKRNWIbY1fVmuLyBgvVV0KWfpnHLL3LTWOLNuPn0ihEfp
nHLMzxa2IodC5LTO5UOABAeMN0ahi9I2goiiOSNLxodzkGABgljSSQKKN1LW2IkmiEAg4rRb_xM3HTLzhhXI2guAi8GLLrZLNTrX2QkNW4LLVwxkheJL2rXO
hRWILc1XDU9AM855LS4LM5Yjk19MO64ruKfOlO15rHUhYXLMlnUmi2gwwiCILbnXrNS55bLzLbnXrNS55bQ_5x0AcQk6AvahiB3QS2MkSWWih1PSYQi-B67L
XoMkX1LOM4suahbwAS2IkMguaha22wi9Ltd2Qi2Lk08BAwvgcIkmiDfm1PQv6d0bSmKMLWEkPAx0mchEbRW22wi9MEAAAwnUmC9gPAwuCbSZi6Ikk39NO66r
uGeihbADAtC55bPSoLpTOSbSSMMkNWPWoLo1XTM0AvahiB1QSoMkmC9g0fQuuWgh5x2mAipLW2jn1HPMIwvahi0oLoEmPAwuCbTWOSMLp1LOXymLL-QgwWei
SmLM8NF5LI5p1LOXh8gmkE8ABAogRyRL8NC55bO3hi32oc0ruWgiVbZrON755LYVXnLOuceehC3IZtWehWwPAx2QcQi-BAxC5LXO3RW2Yok3rGWhiB3gln1N
XymLMDNCLHyML-OABAm6N85bhWnM8NC5LY6ioh2uuWgiGbZLON755LXOvO5L2Il_4ZRY2YmDF0bNZRXwO67LA61nrOWhhC3IpcjmPQuAWMMkId5bhWpMGEOA
B7DLZ2jp1HPMEy_0rI5p1HPMN0rchi0oLs1fzm6uCbU5mCAg55TSWJKGLlubvAeOLrY1XTNEb-VAN1K2oroLueehWpKGLc1nLOmhhC32QkUJSsMkm1h8N75b
hi0Qo5o1PQxwSMMk2e65rJYi9wx0mkeQLro1XTN0TmRBN3NZobo1DH1MN745ra1OWSLLFwwm0WkhdS_BbRa2Qo1pnPMv0ciWSmMMkUh7bRa22wkTxygLkJ9O
xSoLmJ9NOArahi0oLs2zcSmLM5XnDH1NO66r4LU5k08BAx2uMeehh0mMLpDn9NSD8WeieWPS2IcmYEhtHDG0B2755L43i4GKM4WDk19HO16ruaf8WKKKLyf4
O2455b5SYIYmYE8AAR1455X4SOKKM2AAAwB0GeehHM0H1HPIN16bDnHHN675bIH9aYH9aYH9alGB
}


!define IMAGE_AZURE(_alias) ENTITY(rectangle,black,azure,_alias,IMAGE AZURE)
!define IMAGE_AZURE(_alias, _label) ENTITY(rectangle,black,azure,_label, _alias,IMAGE AZURE)
!define IMAGE_AZURE(_alias, _label, _shape) ENTITY(_shape,black,azure,_label, _alias,IMAGE AZURE)
!define IMAGE_AZURE(_alias, _label, _shape, _color) ENTITY(_shape,_color,V,_label, _alias,IMAGE AZURE)
skinparam folderBackgroundColor<<IMAGE AZURE>> White
@enduml