@startuml
sprite $lightstream [200x36/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
888FFFFFFFFFFFFFFFFFFFFFFFFF8888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
88888888888888888888888888888888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
88888888888888888888888888888888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
8888888888888888888888888888888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
888888888888888888888888888888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
F88888888888888888888888888888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
F8888888888888888888888888888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF888888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF888888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF88888FFFFFF88888FFFFFFF88888FFFF
FF8888888888FFFFFFF8888888888FFFFFFF88888FFFFFFFFF88888FFFFF8888888888FFFF88888FFFF88888FF88888888888888FF8888888888FFF88888888888888FF88888888888FFFF888888888888FFFFFF88888FFFFFF88888FFFFFFF88888FFFF
FFF8888888888FFFFFF888888888FFFFFFFF88888FFFFFFFFF88888FFFF888888888888FFF88888FFFF88888FF88888888888888F88888888888FFF88888888888888FF888888888888FFF888888888888FFFFF8888888FFFFF888888FFFFF888888FFFF
FFF8888888888FFFFFF8888FFFFFFFFFFFFF88888FFFFFFFFF88888FFF8888888888888FFF88888FFFF88888FFFFFF88888FFFFFF88888888888FFFFFFF88888FFFFFFF88888F888888FFF88888FFFFFFFFFFFF8888888FFFFF888888FFFFF888888FFFF
FFFF888888888FFFFFFFFFFFFFFFFFFFFFFF88888FFFFFFFFF88888FFF888888FF888888FF88888FFFF88888FFFFFF88888FFFFFF88888FFFFFFFFFFFFF88888FFFFFFF88888FF888888FF88888FFFFFFFFFFFF8888888FFFFF8888888FFF8888888FFFF
FFFF88888FFFFFFFFFFFFFFFFFFFFFFFFFFF88888FFFFFFFFF88888FFF88888FFF888888FF88888FFFF88888FFFFFF88888FFFFFF888888FFFFFFFFFFFF88888FFFFFFF88888FF888888FF88888FFFFFFFFFFF888888888FFFF8888888FFF8888888FFFF
FFFFF8888888888FFFFFFFFFFFFFFFFFFFFF88888FFFFFFFFF88888FFF88888FFFFFFFFFFF88888FFFF88888FFFFFF88888FFFFFF88888888FFFFFFFFFF88888FFFFFFF88888FF888888FF88888FFFFFFFFFFF888888888FFFF88888888F88888888FFFF
FFFFF8888888888888888FFFFFFFFFFFFFFF88888FFFFFFFFF88888FFF88888FFFFFFFFFFF88888888888888FFFFFF88888FFFFFFF8888888888FFFFFFF88888FFFFFFF888888888888FFF88888888888FFFFF8888888888FFF88888888F88888888FFFF
FFFFFF888888888888888888FFFFFFFFFFFF88888FFFFFFFFF88888FFF88888888888888FF88888888888888FFFFFF88888FFFFFFFF8888888888FFFFFF88888FFFFFFF888888888888FFF88888888888FFFF88888888888FFF88888888888888888FFFF
FFFFFFF88888888888888888FFFFFFFFFFFF88888FFFFFFFFF88888FFF88888888888888FF88888888888888FFFFFF88888FFFFFFFFFFF88888888FFFFF88888FFFFFFF88888888888FFFF88888888888FFFF88888888888FFF88888888888888888FFFF
FFFFFFF88888888888888888FFFFFFFFFFFF88888FFFFFFFFF88888FFF88888FFF888888FF88888FFFF88888FFFFFF88888FFFFFFFFFFFFF888888FFFFF88888FFFFFFF88888888888FFFF88888FFFFFFFFF888888F888888FF88888888888888888FFFF
FFFFFFFF888888888888888FFFFFFFFFFFFF88888FFFFFFFFF88888FFF888888FF888888FF88888FFFF88888FFFFFF88888FFFFFFFFFFFFFF88888FFFFF88888FFFFFFF88888F888888FFF88888FFFFFFFFF888888F888888FF88888888888888888FFFF
FFFFFFFF88888888888888FFFFFFFFFFFFFF88888FFFFFFFFF88888FFF8888888F888888FF88888FFFF88888FFFFFF88888FFFFFFFFFFFFF888888FFFFF88888FFFFFFF88888F888888FFF88888FFFFFFFFF88888FFF888888F88888888888888888FFFF
FFFFFFFFF8888888888888FFFFFFFFFFFFFF888888888888FF88888FFFF8888888888888FF88888FFFF88888FFFFFF88888FFFFFFFF88888888888FFFFF88888FFFFFFF88888FF888888FF888888888888F888888FFF888888F88888888888F88888FFFF
FFFFFFFFFF88888888888FFFFFFFFFFFFFFF888888888888FF88888FFFFF88888888888FFF88888FFFF88888FFFFFF88888FFFFFFFF8888888888FFFFFF88888FFFFFFF88888FF888888FF888888888888F888888FFFF88888F88888F88888F88888FFFF
FFFFFFFFFF88888888888FFFFFFFFFFFFFFF888888888888FF88888FFFFFF88888888FFFFF88888FFFF88888FFFFFF88888FFFFFFFFF8888888FFFFFFFF88888FFFFFFF88888FFF88888FF888888888888F88888FFFFF88888F88888FFFFFFF88888FFFF
FFFFFFFFFFF888888888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF888888888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF8888888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF888888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF88888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}


!define IMAGE_LIGHTSTREAM(_alias) ENTITY(rectangle,black,azure,_alias,IMAGE LIGHTSTREAM)
!define IMAGE_LIGHTSTREAM(_alias, _label) ENTITY(rectangle,black,azure,_label, _alias,IMAGE LIGHTSTREAM)
!define IMAGE_LIGHTSTREAM(_alias, _label, _shape) ENTITY(_shape,black,azure,_label, _alias,IMAGE LIGHTSTREAM)
!define IMAGE_LIGHTSTREAM(_alias, _label, _shape, _color) ENTITY(_shape,_color,V,_label, _alias,IMAGE LIGHTSTREAM)
skinparam folderBackgroundColor<<IMAGE LIGHTSTREAM>> White
@enduml