@startuml
sprite $tomcat [100x67/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFADFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6CFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA2CFFFFFFFFFFFFFFFFFFFFFFFFFFFFC3BFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF927FFFFFFFFFFFFFFFFFFFFFFFFFFFF72AFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF823CFFFFFFFFFFFFFFFFFFFFFFFFFFB22AFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7224DFFFFFFEDCCEFFFDBCDEEFFFFD4229FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF72224AECA7543228FFF62223468BB42229FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7222223222222223DFD322222222222229FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF72222222222222229FA222222222222229FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF82222222223542224E7222222222222229FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9222222228CCC922294222222222222229FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA22222229B524C52232222222222222229FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC2222226C322298222222222224542222AFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD322222552222892222222226BCC82222BFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF83222222222289222222228C73222222CFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7322222222A822222226C422222223EFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFECB722222222B62222223B722222225AFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC2222225BBBBECBBBBBBCECBBB4225BEFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE32222236669C6666666BA666532222AFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFECCFB622222222992222222A7222222222DFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEB8657FE832222223C5222222298222222248FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD9655556CE322222227B222222226B2222224AFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA55555559F72222223CC9AAAAAA9AE62222223DFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD65555556EC22222228ED888888BFB42222226FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEA8DFFFF75555899DF977632225BB52138C832226777CFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA556AFFFA5555ADDDFFCBB3222238C96BB422223ACBDFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFE75558DFD65556666AF72222222225EFA2222222223CFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFE968DFB55556AE8555ADCCDFEBA3222225BA8C9322223ABCFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFB655569C7555558855589999AFD7322227C7224AC5222269FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF9555555665555555555555555BF62222244222226522222BFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFDEFB5555555555555555555555556DD4222222222222222228FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFA67CD65555555555555555555555557EC32222222222222226FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFE955569755666555555555555555555558FB322222222222225EFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFE85555555558E85555555555555555555559FB3222222222225EFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFD75555555555AF755555555555555555555559FC42222222226EFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFD755555555555CE6555555555555555555555559FD622222228EFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF8555555555556EC55555555555555555555555558EF932223AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEFD655555555557FA555555555555555555555555557DFC636DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFE79FC65555555558F95555555555555555555555555556AFFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFE855AFB6555555558F8555555555555555555555555555558DFCDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF95555AFB9AABBBAABFA7766555555555555555555555555556867EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFA55568BFFFFFFFFFFFFFFEEDCA9765555555555555555555555557EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFB6557CFFFFFFFFFFFFFFFFFFFFFFFECA8655555555555555555556CFCEFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFD656AEFFFFFFFFFFFFFFFFFFFFFFFFFFFFECA865555555555555558B858EFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFE756BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDB86555555555555655559FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF856BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEB8655555555555557CFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFA55AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDA765555555558DEBBFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFC658FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC96555555688655AFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFE756CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEA755555555555AFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF9558FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC86555555556BFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFC655BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD9655555556CFFFFFFFFFFFFFFFFFFFFFF
FFFFFFE7556DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD965555556CFFFFFFFFFFFFFFFFFFFFF
FFFFFFA5557FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEA6555556DFFFFFFFFFFFFFFFFFFFF
FFFFFD65558FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEA755557CCDEFFFFFFFFFFFFFFFF
FFFFF855558FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEA655555668CFFFFFFFFFFFFFF
FFFFEAAAAACFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEA655555569FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEA6666666AFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDDDDDDEFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}


!define IMAGE_TOMCAT(_alias) ENTITY(rectangle,black,azure,_alias,IMAGE TOMCAT)
!define IMAGE_TOMCAT(_alias, _label) ENTITY(rectangle,black,azure,_label, _alias,IMAGE TOMCAT)
!define IMAGE_TOMCAT(_alias, _label, _shape) ENTITY(_shape,black,azure,_label, _alias,IMAGE TOMCAT)
!define IMAGE_TOMCAT(_alias, _label, _shape, _color) ENTITY(_shape,_color,V,_label, _alias,IMAGE TOMCAT)
skinparam folderBackgroundColor<<IMAGE TOMCAT>> White
@enduml